[package]
name = "cameraplugin"
version = "0.2.2"
authors = ["cbl_dev"]
edition = "2021"

[package.metadata.skyline]
titleid = "0100a6301214e000" # Fire Emblem Engage

[lib]
crate-type = ["cdylib"]

# Force the compiler to use a specific skyline version
[dependencies]
skyline = { git = "https://github.com/Raytwo/skyline-rs", branch = "preview" }
engage = { git = "https://github.com/DivineDragonFanClub/engage", default-features = false }
unity = { git = "https://github.com/DivineDragonFanClub/unity", default-features = false }

# Force a specific version of nnsdk
nnsdk = { git = "https://github.com/ultimate-research/nnsdk-rs", rev = "9c13b526" }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true

# Patch only crates.io to use the git version
[patch.crates-io]
nnsdk = { git = "https://github.com/ultimate-research/nnsdk-rs", rev = "9c13b526" }